# Operaciones básicas con el grafo de computación en TensorFlow

El paradigma computacional de TensorFlow es el _dataflow paradigm_ como se había mencionado anteriormente en otra libreta. Esto significa que TensorFlow requiere que primero se cree un **grafo** de computación donde _todas_ las operaciones están descritas y detalladas, para que posteriormente se ejecuten en el orden en que se establecieron.

Este diseño es más intuituvo al hablar de _capas_ de cálculos y operaciones como se verá posteriormente, además de que permite el parelelizamiento de algoritmos que sean computacionalmente muy intensivos.

En esta libreta se explorarán las operaciones básicas al crear un _grafo_ de computación y el cómo se desarrollan, ejecutan, asi como llegar al resultado final.

In [9]:
# Importar las librerías necesarias
import tensorflow as tf
import numpy as np

# Crear una sesión de TensorFlow (i.e. un grafo de computación)
session = tf.Session()

## Operaciones simples (1 capa de computación en el grafo)

Como primer ejemplo, se pretende hacer un modelo muy _simple_ de una regresión lineal que siga la ecuación $$y = 3x.$$

Para lograr este objetivo se creará el tensor de valores de $x$ a partir de arreglos.

In [10]:
# Crear un arreglo de numpy con los valores
x_vals = np.array([2., 4., 6., 8., 10., 12.])

In [11]:
# Crear un placeholder de TensorFlow de tipo flotante
x_data = tf.placeholder(tf.float32)

In [12]:
# Definir la constante del modelo
m_const = tf.constant(3.0)

In [13]:
# Definir la operación de multiplicación dentro del grafo
my_product = tf.multiply(m_const, x_data)

In [14]:
# Y notar que es un objeto de TensorFlow
my_product

<tf.Tensor 'Mul_1:0' shape=<unknown> dtype=float32>

In [15]:
# Iterar sobre los valores y ejecutar el grafo de computación para encontrar los valores de y
for x_val in x_vals:
    # Se debe suministrar los valores en un diccionario de Python para su evaluación
    print(session.run(my_product, feed_dict={x_data: x_val}))

6.0
12.0
18.0
24.0
30.0
36.0


## Operaciones múltiples (múltiples capas de computación en el grafo)

Ahora se realizará un ejemplo donde múltiples operaciones se llevan a cabo en el grafo computacional, en particular se harán un par de multiplicación de arreglo multidimensionales utilizando TensorFlow.

Ahora, la operación que se desea realizar es la siguiente:

$$ \left( X \cdot m_1 \right) \cdot m_2 + a_1$$

donde $X \in \mathbb R_{3\times4}$, $m_1 \in \mathbb R^4$ y $m_2, a_1 \in \mathbb R.$

In [16]:
# Se crea una nueva sesión de TensorFlow (un nuevo grafo computacional)
session = tf.Session()

In [17]:
# Crear un arreglo multidimensional de tamaño (3,4)
arreglo_1 = np.array([[1.,3.,5.,7.],
                     [-2.,0.,7.,6.],
                     [-6.,-1.,0.,3.]])
# Ver que el arreglo esté bien inicializado
arreglo_1

array([[ 1.,  3.,  5.,  7.],
       [-2.,  0.,  7.,  6.],
       [-6., -1.,  0.,  3.]])

In [23]:
# Se crea un nuevo arreglo multidimensional utilizando el arreglo anterior.
x_vals = np.array([arreglo_1, arreglo_1+1])
# Y se verifica que esté bien hecho
x_vals

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [20]:
# Para crear los datos en el grafo, se crea un placeholder
x_data = tf.placeholder(tf.float32, shape=(3,4))

In [21]:
# Se crean ahora tres constantes diferentes
# Primero, un arreglo unidimensional de constantes, tamaño (1,4)
m_1 = tf.constant([[1.], [0.], [-2.], [5.]])
# Y luego dos constantes por separado
# Notar que también son arreglos para mantener consistencia en el grafo de computación
m_2 = tf.constant([[7.]])
a_1 = tf.constant([[15.]])

In [27]:
# Ahora se implementa el modelo propuesto
# Primero, la multiplicación del arreglo multidimensional por el unidimensional
prod_1 = tf.matmul(x_data, m_1)
# Luego se realiza la siguiente multiplicación, del resultado con la constante
# Adicionalmente, se puede utilizar la sintáxis especial de multiplicación de arreglos multidimensionales
prod_2 = prod_1 @ m_2
# Y por último se suma la última constante al resultado anterior
add_1 = tf.add(prod_2, a_1)

In [28]:
# Ahora se ejecuta todo el grafo de computación
for x_val in x_vals:
    print(session.run(add_1, feed_dict={x_data: x_val}))

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]
